{
    "whyyoutouzhele": "李老师不是你老师啊",
    "wangzhian8848": "王局志安",
    "newszg_official": "新闻调查",
    "wangdan1989": "王丹",
    "hrw_chinese": "人权观察中文",
    "fangshimin": "方世民",
    "badiucao": "巴丢草",
    "zaobaosg": "联合早报",
    "dajiyuan": "大纪元",
    "NTDChinese": "新唐人",
    "VOAChinese": "美国之音中文",
    "hrw": "人权观察",
    "FreedomHouse": "自由之家",
    "ASPI_org": "澳大利亚战略政策研究所",
    "CaoChangqing": "曹长青",
    "FDD": "FDD智库",
    "SophieDRich": "苏菲·理查森",
    "amnesty": "国际特赦组织",
    "bbc.com": "BBC中文",
    "dw.com": "德国之声",
    "rfi.fr": "法国国际广播电台",
    "cn.nytimes.com": "纽约时报中文网"
}
